<a href="https://colab.research.google.com/github/TovarischComrad/Tehnopark/blob/main/LinearClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_csv('results.csv')
df

,Unnamed: 0,Hindi,English,Science,Maths,History,Geograpgy,Total,Results,Div
0,0,65,10,59,3,71,37,245,0,3
1,1,94,56,4,67,91,50,362,1,1
2,2,7,85,76,99,60,25,352,0,2
3,3,88,46,59,94,52,38,377,1,1
4,4,39,81,37,38,6,54,255,1,3
...,...,...,...,...,...,...,...,...,...,...
995,995,55,89,68,58,13,13,296,0,2
996,996,42,62,25,87,51,68,335,1,2
997,997,9,83,70,14,11,78,265,0,3
998,998,23,82,31,42,84,52,314,0,2
999,999,75,78,68,33,79,91,424,1,1

In [2]:
df.columns

Index(['Unnamed: 0', 'Hindi', 'English', 'Science', 'Maths', 'History',
       'Geograpgy', 'Total', 'Results', 'Div'],
      dtype='object')

In [6]:
lst = ['Hindi', 'English', 'Science', 'Maths', 'History',
       'Geograpgy', 'Results']

In [7]:
df = df[lst]
df

     Hindi  English  Science  Maths  History  Geograpgy  Results
0       65       10       59      3       71         37        0
1       94       56        4     67       91         50        1
2        7       85       76     99       60         25        0
3       88       46       59     94       52         38        1
4       39       81       37     38        6         54        1
..     ...      ...      ...    ...      ...        ...      ...
995     55       89       68     58       13         13        0
996     42       62       25     87       51         68        1
997      9       83       70     14       11         78        0
998     23       82       31     42       84         52        0
999     75       78       68     33       79         91        1

[1000 rows x 7 columns]

In [9]:
df.isnull().sum()

Hindi        0
English      0
Science      0
Maths        0
History      0
Geograpgy    0
Results      0
dtype: int64

In [11]:
X = df[lst[:-1]]
X

     Hindi  English  Science  Maths  History  Geograpgy
0       65       10       59      3       71         37
1       94       56        4     67       91         50
2        7       85       76     99       60         25
3       88       46       59     94       52         38
4       39       81       37     38        6         54
..     ...      ...      ...    ...      ...        ...
995     55       89       68     58       13         13
996     42       62       25     87       51         68
997      9       83       70     14       11         78
998     23       82       31     42       84         52
999     75       78       68     33       79         91

[1000 rows x 6 columns]

In [14]:
y = df['Results']
y

0      0
1      1
2      0
3      1
4      1
      ..
995    0
996    1
997    0
998    0
999    1
Name: Results, Length: 1000, dtype: int64

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [43]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression().fit(X_train, y_train)

y_pred = clf.predict(X_test)

In [44]:
X_test

     Hindi  English  Science  Maths  History  Geograpgy
521     58        2       62     29       51         30
737     77       60       44     86       47         22
740      2       20       96     15       39         51
660     37       29       79     87       40         88
411     65       69        4     53       11         66
..     ...      ...      ...    ...      ...        ...
468     94       79       31     89       79         13
935     95       49       27     79       75         49
428     51       43       86     24       43         68
7       18       23       97     65       15         20
155     95       13       19     49       50         76

[300 rows x 6 columns]

In [45]:
y_pred

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0])

$accuracy = \frac{TP + }{TP + TN + FP + FN}$

In [46]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.8

$precision = \frac{TP}{TP + FP}$

In [47]:
from sklearn.metrics import precision_score

precision_score(y_test, y_pred)

0.6847826086956522

$recall = \frac{TP}{TP + FN}$

In [48]:
from sklearn.metrics import recall_score

recall_score(y_test, y_pred)

0.6702127659574468

$F = \frac{2\cdot precision \cdot recall}{precision + recall}$

In [49]:
from sklearn.metrics import f1_score

f1_score(y_test, y_pred)

0.6774193548387096

In [61]:
marks = [[63, 72, 35, 52, 65, 42]]
df2 = pd.DataFrame(marks, columns=lst[:-1])

In [62]:
res = clf.predict(df2)

In [63]:
res[0]

0

In [64]:
def mark_predict(hindi, english, science, maths, history, geography):
  marks = [[hindi, english, science, maths, history, geography]]
  df2 = pd.DataFrame(marks, columns=lst[:-1])
  result = clf.predict(df2)[0]
  return result

In [65]:
mark_predict(52, 63, 99, 58, 13, 73)

1